### ISSUE TITLE
Anmerkung Verständnis 

### ISSUE THREAD

**Issue by eikeschott** [GeoMOER-Students-Space/mpg-envinfosys-teams-2018-rs_18_axmideda#2]
https://github.com/GeoMOER-Students-Space/mpg-envinfosys-teams-2018-rs_18_axmideda/blob/1459be1c4d882fc7fa9e610ba42d469b472cc7a7/src/assignment_02_code_snippets.R#L54

Wahnsinns Funktion :+1: an der Stelle könnte man gut eine weitere Funktionsvariable einführen, sodass der Pfad beim Ausführen der Funktion selbst setzbar ist und diese Funktion nicht "Festgeschrieben" für diesen Pfad steht.

**Comment by goergen95** [comment]
Angepasst! über path = "" beim funktionsaufruf kann jetzt ein directory angegben werden. In diesem directory wird evaluiert, ob bereits merged raster vorhanden sind. falls nicht werden diese in das directory geschrieben.
