### ISSUE TITLE
Anmerkung / Verständnis 

### ISSUE THREAD

**Issue by eikeschott** [GeoMOER-Students-Space/mpg-envinfosys-teams-2018-rs_18_axmideda#3]
https://github.com/GeoMOER-Students-Space/mpg-envinfosys-teams-2018-rs_18_axmideda/blob/1459be1c4d882fc7fa9e610ba42d469b472cc7a7/src/assignment_02_code_snippets.R#L60

Hier habe ich noch nicht ganz Verstanden, wo der Merge befehl an sich ist. 
Es wird ein Objekt gesetzt (rmerge) das aber dann ohne Funktionsaufruf gefüllt wird

**Comment by goergen95** [comment]
Danke für den Hinweis ;) muss zwischen irgendwelchen commits abhanden gekommen sein!

**Comment by goergen95** [comment]
Jetzt ist es mir aufgefallen: an der Stelle und aufgrund der besonderheit der Daten (NA als 255 codiert) braucht es hier keine eigene funktion wie merge(). eine einfache addition der raster daten und anschließende substraktion von 255 reicht aus.
